python src/example_noise_models.py bank_binary_marital_equally_noisy config/noise_models_comparison.ini
python src/example_noise_models.py bank_binary_marital_color_0_gains_more config/noise_models_comparison.ini
python src/example_noise_models.py bank_binary_marital_color_1_gains_more config/noise_models_comparison.ini
